[pytest]
reruns = 1
log_cli = True
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] | %(funcName)s | %(filename)s:%(lineno)s | %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
markers =
    test: 自定义的通用测试标记说明
    china: 与国内相关功能测试的标记说明
    abroad: 与国外相关功能测试的标记说明
    increment: 与增量用例相关功能测试的标记说明
    full_amount: 与全量用例相关功能测试的标记说明